runtime: python37
entrypoint: gunicorn -b :8080 poliastro_live.wsgi

handlers:
# redirect Sphinx extension
# request /static/live-filename
- url: /static/live-(.*)\.css
  static_files: static/sympy-live/css/live-\1.css
  upload: static/(.*)
  secure: always
- url: /static/live-(.*)\.js
  static_files: static/sympy-live/javascript/live-\1.js
  upload: static/(.*)
  secure: always
- url: /static/external/classy\.js
  static_files: static/external/javascript/classy.js
  upload: static/(.*)
  secure: always
- url: /static/utilities\.js
  static_files: static/sympy-live/javascript/utilities.js
  upload: static/(.*)
  secure: always

- url: /static
  static_dir: static
  expiration: 1d
  secure: always

- url: /google5acf6d2992c8237d.html
  static_files: google5acf6d2992c8237d.html
  upload: google5acf6d2992c8237d.html
  secure: always

# cache-busting scheme
# request /static-(app version)/filename
- url: /static-[0-9]+/(.*)
  static_files: static/\1
  upload: static/(.*)
  secure: always

# if you're adding the shell to your own app, change this regex url to the URL
# endpoint where you want the shell to run, e.g. /shell . You'll also probably
# want to add login: admin to restrict to admins only.
- url: .*
#  script: shell.application
  script: auto
  secure: always
